export default {
    "OMOTOSHO 2" : ['TR4', 'TR3'],
    "EKET" : ['E21M', 'E22M'],
    "PORTHARCOURT MAIN" : ['M21P'],
    "AFAM 6" : ['ADA200', 'ADB200'],
    "ALAOJI" : ['L7A', 'L8A'],
    "LOKOJA TS" : ['L7G', 'J2L', 'J1L', 'L6G'],
    "SAPELE NIPPPs" : ['ST1', 'GT2', 'ST3', 'GT4', 'GT3', 'GT1'],
    "OMOTOSHO NIPPPS" : ['TR2', 'TR3', 'TR4', 'TR1'],
    "ODUKPANI GS" : ['D2B', 'D1B'],
    "OMOTOSHO 1" : ['TR1', 'TR2'],
    "DELTA 3" : ['TR6', 'TR5'],
    "EKIM" : ['EK1M'],
    "GEREGU PS" : ['GT11', 'R2J', 'R1J', 'GT12', 'GT13'],
    "IKOT EKPENE" : ['K2U', 'K1U', 'K4U', 'K3U', 'D2K', 'A1K', 'A2K', 'D1K'],
    "RIVERS IPPPS" : ['GT1'],
    "GWAGWALADA TS" : ['G5B', 'R5G'],
    "OMOKU GS" : ["O1R"],
    "IHOVBOR TS" : ["GT1", "GT2", "GT3", "GT4", "OHL1", "OHL2"]
};
