const stationsKey = {
    "OMOTOSHO 2" : 'omotosho2',
    "EKET" : 'eket',
    "PORTHARCOURT MAIN" : 'phMain',
    "AFAM 6" : 'afamViTs',
    "ALAOJI" : 'alaoji',
    "LOKOJA TS" : 'lokojaTs',
    "SAPELE NIPPP" : 'sapeleNippPs',
    "OMOTOSHO NIPPP" : 'omotoshoNippPs',
    "ODUKPANI GS" : 'odukpaniGs',
    "OMOTOSHO 1" : 'omotosho1',
    "OMOTOSHO GAS" : 'OMOTOSHO GAS',
    "DELTA 3" : 'delta3',
    "EKIM" : 'ekim',
    "GEREGU PS" : 'gereguPs',
    "IKOT EKPENE" : 'ikotEkpene',
    "RIVERS IPPPS" : 'riversIppPs',
    "GWAGWALADA TS" : 'gwagwalada',
    "OMOKU GS" : 'omokuPs1',
    "IHOVBOR TS" : 'ihovborNippPs',
    "OLORUNSOGO NIPP": 'olorunsogo1',
    "DELTA 2" : 'delta2',
    "UGWUAJI" : 'ugwuaji',
    "ASABA" : 'asaba',
    "PARAS ENERGY": 'parasEnergyPs',
    "AZURA": 'AZURA',
    "TRANS AMADI" : 'TRANS AMADI',
    "IBOM POWER" : 'IBOM POWER',
    "GBARAIN" : 'gbarain',
    "OLORUNSOGO GAS": 'olorunsogoPhase1Gs',
    "OKPAI GS" : 'okpaiGs',
    "JEBBA GS" : 'jebbaTs',
    "DADINKOWA GS" : 'dadinKowaGs',
    "KAINJI GS" : 'kainjiTs',
    "EGBIN GS" : 'egbinPs',
    "AFAM IV GS" : 'afamIv_vPs',
    "SHIRORO GS" : 'shiroroPs',
    "DELTA 4" : 'deltaGs'
};

export default stationsKey;
