export default {
    "OMOTOSHO 2" : ['TR4', 'TR3', 'OMOTOSHO 2'],
    "EKET" : ['E21M', 'E22M', 'EKET'],
    "PORTHARCOURT MAIN" : ['M21P', 'PORTHARCOURT MAIN'],
    "AFAM VI" : ['ADA200', 'ADB200', 'AFAM VI'],
    "ALAOJI" : ['L7A', 'L8A', 'ALAOJI'],
    "SAPELE NIPPP" : [ 'GT2', 'GT4', 'GT3', 'GT1', 'SAPELE NIPPP'],
    "SAPELE STEAM" : ['ST1', 'ST3', 'SAPELE STEAM'],
    "LOKOJA TS" : ['L7G', 'J2L', 'J1L', 'L6G', 'LOKOJA TS'],
    "ODUKPANI GS" : ['D2B', 'D1B', 'ODUKPANI GS'],
    "OMOTOSHO 1" : ['TR1', 'TR2', 'OMOTOSHO 1'],
    "DELTA 3" : ['TR6', 'TR5', 'DELTA 3'],
    "EKIM" : ['EK1M', 'EKIM'],
    "GEREGU GAS" : ['GT11', 'R2J', 'R1J', 'GT12', 'GT13', 'GEREGU GAS'],
    "IKOT EKPENE" : ['K2U', 'K1U', 'K4U', 'K3U', 'D2K', 'A1K', 'A2K', 'D1K', 'IKOT EKPENE'],
    "RIVERS IPPPS" : ['GT1', 'RIVERS IPPPS'],
    "GWAGWALADA TS" : ['G5B', 'R5G', 'GWAGWALADA TS'],
    "OMOKU GS" : ["O1R", "OMOKU GS"],
    "IHOVBOR TS" : ["GT1", "GT2", "GT3", "GT4", "OHL1", "OHL2", "IHOVBOR TS"],
    "OLORUNSOGO NIPP": ["TR1", "TR2", "OLORUNSOGO 1"],
    "DELTA 2" : ['TR3', 'TR4', 'DELTA 2'],
    "UGWUAJI" : ['U1A', 'U2A', 'UGWUAJI'],
    "ASABA" : ['B3D', 'D3T', 'ASABA'],
    "PARAS ENERGY" : ['132CB', 'PARAS ENERGY'],    
    "OMOTOSHO NIPPP" : ['TR2', 'TR3', 'TR4', 'TR1', 'OMOTOSHO NIPPP'],
    "OMOTOSHO GAS" : ['OMOTOSHO GAS'],
    'GEREGU NIPP' : ['GEREGU NIPP'],
    'AZURA' : ['AZURA'],
    'TRANS AMADI' : ['TRANS AMADI'],
    'IBOM POWER' : ['IBOM POWER'],
    "OLORUNSOGO GAS": ['R2A', 'R1W', 'TR3', 'TR4', "OLORUNSOGO GAS"],
};
